[Version]
Class=IEXPRESS
SEDVersion=3
[Options]
PackagePurpose=InstallApp
ShowInstallProgramWindow=1
HideExtractAnimation=0
UseLongFileName=1
InsideCompressed=0
CAB_FixedSize=0
CAB_ResvCodeSigning=0
RebootMode=N
InstallPrompt=%InstallPrompt%
DisplayLicense=%DisplayLicense%
FinishMessage=%FinishMessage%
TargetName=%TargetName%
FriendlyName=%FriendlyName%
AppLaunched=%AppLaunched%
PostInstallCmd=%PostInstallCmd%
SourceFiles=SourceFiles
[Strings]
InstallPrompt=
DisplayLicense=
FinishMessage=
TargetName=C:\Users\dimon\zcode-russifier\installer\ZCodeRussifier-setup.exe
FriendlyName=ZCode Russifier Setup
AppLaunched=run.cmd
PostInstallCmd=<None>
SourceFiles=SourceFiles
[SourceFiles]
SourceFiles0=C:\Users\dimon\zcode-russifier\
SourceFiles1=C:\Program Files\nodejs\
[SourceFiles0]
russify.js=
run.cmd=
translations\ru-menu.json=
translations\ru-part1.json=
translations\ru-part2.json=
translations\ru-part3.json=
translations\ru-part4.json=
translations\ru-set1.json=
translations\ru-set10.json=
translations\ru-set11.json=
translations\ru-set12.json=
translations\ru-set13.json=
translations\ru-set14.json=
translations\ru-set15.json=
translations\ru-set16.json=
translations\ru-set17.json=
translations\ru-set18.json=
translations\ru-set19.json=
translations\ru-set2.json=
translations\ru-set20.json=
translations\ru-set21.json=
translations\ru-set22.json=
translations\ru-set3.json=
translations\ru-set4.json=
translations\ru-set5.json=
translations\ru-set6.json=
translations\ru-set7.json=
translations\ru-set8.json=
translations\ru-set9.json=
[SourceFiles1]
node.exe=
